dist: xenial
language: python
python:
    - "3.7"
before_install:
    - sudo apt update
    - sudo apt install tesseract-ocr
    - sudo apt install libtesseract-dev
    - sudo apt install poppler-utils
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python -m unittest
